#ifndef FPPE_VERSION_H
#define FPPE_VERSION_H
//TODO this file should be generated

#define FPPE_VERSION_MAJOR 1
#define FPPE_VERSION_MINOR 18

#define FPPE_VERSION_BUILD 5

//must be consistent with library header
#define  FPPE_VERSION_RELEASE_ID_ALFA 0
#define  FPPE_VERSION_RELEASE_ID_BETA 1
#define  FPPE_VERSION_RELEASE_ID_RC   2
#define  FPPE_VERSION_RELEASE_ID_RELEASE 3

#define  FPPE_VERSION_RELEASE_ID_GAMMA 5
#define  FPPE_VERSION_RELEASE_ID_DELTA 6
#define  FPPE_VERSION_RELEASE_ID_EPSILON 7

#define  FPPE_VERSION_RELEASE_ID_11 11
#define  FPPE_VERSION_RELEASE_ID_12 12


#define  FPPE_VERSION_RELEASE_ID FPPE_VERSION_RELEASE_ID_ALFA

#endif
