ModelDataToTPNConverter.exe --input_model track1/RAMP_out.log --output_tpn track1/tpn.dat
ModelDataToTPNConverter.exe --input_model track2/RAMP_out.log --output_tpn track2/tpn.dat
ModelDataToTPNConverter.exe --input_model track3/RAMP_out.log --output_tpn track3/tpn.dat
ModelDataToTPNConverter.exe --input_model track4/RAMP_out.log --output_tpn track4/tpn.dat
ModelDataToTPNConverter.exe --input_model track5/RAMP_out.log --output_tpn track5/tpn.dat
ModelDataToTPNConverter.exe --input_model track6/RAMP_out.log --output_tpn track6/tpn.dat
ModelDataToTPNConverter.exe --input_model track7/RAMP_out.log --output_tpn track7/tpn.dat
ModelDataToTPNConverter.exe --input_model track8/RAMP_out.log --output_tpn track8/tpn.dat
ModelDataToTPNConverter.exe --input_model track9/RAMP_out.log --output_tpn track9/tpn.dat
ModelDataToTPNConverter.exe --input_model track10/RAMP_out.log --output_tpn track10/tpn.dat
ModelDataToTPNConverter.exe --input_model track11/RAMP_out.log --output_tpn track11/tpn.dat
ModelDataToTPNConverter.exe --input_model track12/RAMP_out.log --output_tpn track12/tpn.dat
ModelDataToTPNConverter.exe --input_model track13/RAMP_out.log --output_tpn track13/tpn.dat
ModelDataToTPNConverter.exe --input_model track14/RAMP_out.log --output_tpn track14/tpn.dat
ModelDataToTPNConverter.exe --input_model track15/RAMP_out.log --output_tpn track15/tpn.dat
ModelDataToTPNConverter.exe --input_model track16/RAMP_out.log --output_tpn track16/tpn.dat
ModelDataToTPNConverter.exe --input_model track17/RAMP_out.log --output_tpn track17/tpn.dat
ModelDataToTPNConverter.exe --input_model track18/RAMP_out.log --output_tpn track18/tpn.dat
ModelDataToTPNConverter.exe --input_model track19/RAMP_out.log --output_tpn track19/tpn.dat
ModelDataToTPNConverter.exe --input_model track20/RAMP_out.log --output_tpn track20/tpn.dat